### PR TITLE
better late than never, y'all!

### PR DESCRIPTION
**Pull request by brandarchist**

### CODE REVIEW

**Comment by Yuffster** [comment]
You're actually ahead of the curve.  Only three other people have submitted a solution to this one.

**Comment by brandarchist** [comment]
I actually had some thoughts on the class that I hope you don't mind my sharing:

It seems that, this week, only two people have submitted a solution, which is a low number considering the class attendance. I think that a lot of people may have been unclear on the pre-requisite knowledge required for the class as, initially anyway, the simplistic explanations of bash, ssh keys, etc. seemed to be targeted at the beginner. The more recent lessons, however, seem to be geared more towards people with existing knowledge on the topic. Perhaps the point is for people to go obtain/google the knowledge they are missing on their own, but I'm not certain they are aware of that. 

I can certainly appreciate not wanting to "talk down" to any of the attendees but it would seem as if many of them are still having trouble just getting Ruby installed on their machines. I'd like to offer a few suggestions:

• Do an off-schedule, class review of each of the problems and solutions. Taking time to explain (meticulously) the diff's between the initial files and the end result
• Ask people in the class who are excelling (Austin, Donny, myself-ish) to be available to assist people one-on-one to prevent them from being left behind entirely… I am, of course, offering my time in this
• Host, coordinate, endorse, etc a secondary class for people to play catchup and have concepts re-explained… As above, I am offering my time to do this with little more than an OK from you

One more thing... I am fairly new to the Dojo and you seem like the obvious person to ask: I wanted to host my own class (iOS Development: demo apps with only two lines of code). What is the best way to do this?

**Comment by Yuffster** [comment]
Great points, definitely.

I think the next time I do the course, I'll schedule a second two hours a week as "office hours" where people can drop in to get additional help when needed.  I also want to integrate the grokthestack.com site and GitHub to better keep track of completion status and give people a place to ask/answer questions.

You're right about the Googling.  Looking up information is an important part of being a developer, so it's a good skill to practice.  However, the notes themselves generally contain the solutions to the problem, just munged a bit to prevent direct copying.

I'm not sure it would be a good idea to walk through the solutions, since that means the student never has the ability to figure it out on their own, which is valuable experience.  It's definitely worth thinking about, though.

**Comment by Yuffster** [comment]
Oh, and hosting is easy, just submit the event at http://events.hackerdojo.com and wait for approval. :)

**Pull request closed without merging**
